Ankand-Auction/ankand/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

# Override the 3 most important variables
admin.site.site_header = "Ankand Admin"
admin.site.site_title = "Ankand Admin Portal"
admin.site.index_title = "Welcome to Ankand Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('', include('auctions.urls')),
    path('', include('users.urls')),
    path('', include('messaging.urls')),
    path('', include('payments.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ankand-Auction/auctions/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path('auctions/', views.auctions, name='auctions'),
    path('auction-add', views.auction_add, name='auction-add'),
    path('auction/edit/<str:slug>', views.auction_edit, name='auction-edit'),
    path('auction-details/<str:slug>/', views.auction_details, name='auction-details'),
    path('auction/delete/<str:slug>', views.auction_delete, name='auction-delete'),

    # Auctions
    path('auctions-submit' , views.auctions_submit, name='auctions-submit'),
    path('auctions-submit-ajax' , views.auctions_submit_ajax, name='auctions-submit-ajax'),
    path('auctions/bid/<str:slug>', views.auctions_bid_details, name='auction-bid-details'),
    path('auctions-mybids/' , views.auctions_mybids, name='auctions-mybids'),
    path('auction-my-bid-delete/<int:id>' , views.auction_mybid_delete, name='auction-my-bid-delete'),
    path('auctions-mybids/details/<str:slug>' , views.auctions_mybids_details, name='auctions-mybids-details'),
    path('auctions-winning', views.winning_bids, name='auctions-winning'),
    path('auctions-closed', views.closedAuctions, name='auction-closed'),

    # Auction Vendor Product List
    path('auctions/vendor/<str:author>', views.auctions_vendor_list, name='auctions-vendor'),

    # Direct Buy
    path('buy-it-now/<str:slug>', views.buy_it_now, name='buy-it-now'),
    path('confirm/order/<str:slug>', views.confirm_order, name='confirm-order'),
    path('success/order', views.success_order, name='success-order'),
    path('auction-billing/<str:slug>', views.auction_billing, name='auction-billing'),
    path('export-invoice/<int:invoice_id>/', views.export_invoice, name='export-invoice'),

    # My Orders
    path('my-orders/' , views.my_orders, name='my-orders'),

    # Search
    path('search' , views.searching, name='search'),

    # Invoice
    path('auction-invoice/<str:slug>', views.auction_invoice, name='auction-invoice'),

    path('rating/<str:id>', views.rating, name='rating'),

    path('notification-details/<str:id>', views.notification_details, name='notification-details'),

    path('reports' , views.reports, name='reports'),

    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ankand-Auction/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/auth/login.html'), name='login'),
    path('logout', views.user_logout ,name='logout'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('change/password/', views.change_password, name='change-password'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/auth/password-reset/password_reset_form.html',
        html_email_template_name='users/auth/password-reset/html_password_reset_email.html',
        subject_template_name='users/auth/password-reset/password_reset_subject.txt',
        success_url='/password_reset_done/'
    ), name='password-reset'),

    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/auth/password-reset/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/auth/password-reset/password_reset_confirm.html',
        success_url='/password_reset_complete/'
    ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/auth/password-reset/password_reset_complete.html'
    ), name='password_reset_complete'),

    # User Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),

    path('profile/payment-settings/<str:username>/', views.profile_payment_settings, name='profile-payment-settings'),
]

Ankand-Auction/auctions/models.py
import uuid
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from autoslug import AutoSlugField
from users.models import UserProfile
from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image
from django.urls import reverse
from django.core.validators import *
from django.core.validators import MaxValueValidator, MinValueValidator


class Category(models.Model):
    STATUS_CHOICES = [
        (True, 'Active'),
        (False, 'Deactive'),
    ]
    DEFAULT = 'icons/314870_edit_clipboard_icon.svg'

    title = models.CharField(max_length=200, null=False , blank=False)
    slug = AutoSlugField(populate_from='title', unique=True)  # Populate from 'title' and ensure uniqueness
    status = models.BooleanField(default=True, choices=STATUS_CHOICES)
    icon = models.FileField(upload_to="icons", validators=[FileExtensionValidator(['svg'])], null=True, blank=True, default=DEFAULT)
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.title



class Auction(models.Model):
    STATUS_CHOICES = [
        (True, 'Active'),
        (False, 'Deactive'),
    ]

    CONDITION_CHOICES = [
        ('New', 'New'),
        ('Used', 'Used'),
        ('Brand New', 'Brand New'),
        ('Like New', 'Like New'),
        ('Very Good', 'Very Good'),
        ('New with tags', 'New with tags'),
        ('New without tags', 'New without tags'),
        ('New with defects', 'New with defects'),
        ('For parts or not working', 'FCR parts or not working'),
        ('Seller refurbished', 'Seller refurbished'),
    ]

    TYPE_CHOICES = [
        ('', 'Select One'), 
        ('auction', 'Auction'),
        ('buy-it-now', 'Buy-It-Now'),
        ('auction & buy-it-now', 'Auction & Buy-It-Now'),
    ]
    
    title = models.CharField(max_length=200, null=False , blank=False)
    slug = AutoSlugField(populate_from='title', unique=True)  # Populate from 'title' and ensure uniqueness
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    description = models.TextField(max_length=200, null=True)
    details_description = models.TextField(max_length=1024, null=True)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='', blank=False, null=False)
    price = models.DecimalField('Auction Starting Price', max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    started_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    reserve_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    direct_buy = models.DecimalField('Buy It Now Price', max_digits=10, decimal_places=2, blank=True, null=True, default=0.00)
    bid_increments = models.IntegerField(default=0)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    image = models.ImageField(upload_to='images/')
    image1 = models.ImageField(null=True, blank=True, upload_to='images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='images/')
    condition = models.CharField(max_length=50, choices=CONDITION_CHOICES, default='New')
    started_date = models.DateTimeField(default=timezone.now)
    expired_date = models.DateTimeField(default=datetime.now()+timedelta(days=7))
    status = models.BooleanField(default=True, choices=STATUS_CHOICES)
    open_status = models.IntegerField(default=0)
    closed = models.BooleanField(default=False)
    amount_of_bids = models.IntegerField(default=0)
    winnerBid = models.ForeignKey('Bidder', blank=True, null=True, on_delete=models.CASCADE, related_name='winner')
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    @property
    def expired(self):
        expiry = self.expired_date.replace(tzinfo=None)
        now = timezone.now().replace(tzinfo=None)
        if now > expiry:
            return True
        return False

    def __str__(self):
        return self.title   
    
    def highest_bid(self):
        return Bidder.objects.filter(item=self).order_by('-bid_amount').first()
    
    def get_absolute_url(self):
        return reverse('auction-details', kwargs={'slug' : self.slug})
    
    # # override save method
    # def save(self, *args, **kwargs):
    #     # call parent save method
    #     super(Auction, self).save(*args, **kwargs)
    #     img = Image.open(self.image.path)

    #     output_size = (400, 600)
    #     img.thumbnail(output_size)
    #     img.save(self.image.path)


class Bidder(models.Model):
    TYPE_CHOICES = [
        ('auction', 'Auction'),
        ('buy-it-now', 'Buy-It-Now'),
    ]
        
    numeric = RegexValidator(r'^[0-9]*$', 'Only numerics are allowed.')

    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    bid_amount = models.CharField(max_length=255, validators=[numeric])
    winningBid = models.BooleanField(default=False)
    paid_status = models.BooleanField(default=False)
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='', blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message


class BillingAddress(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    email = models.EmailField(blank=True, null=True)  # Include email as a separate field
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    address = models.TextField(blank=True, null=True, default='')
    state = models.CharField(max_length=100, blank=True, null=True, default='')
    city = models.CharField(max_length=100, blank=True, null=True, default='')
    street = models.CharField(max_length=150, blank=True, null=True, default='')
    house = models.CharField(max_length=150, blank=True, null=True, default='')
    zip_code = models.CharField(max_length=10, blank=True, null=True, default='')
    postal_code = models.CharField(max_length=10, blank=True, null=True, default='')
    phone = PhoneNumberField(default='')
    same_as_shipping = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f'Billing Address For {self.user}'
    

class ShippingAddress(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    billing = models.ForeignKey(BillingAddress, on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)  # Include email as a separate field
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    address = models.TextField(blank=True, null=True, default='')
    state = models.CharField(max_length=100, blank=True, null=True, default='')
    city = models.CharField(max_length=100, blank=True, null=True, default='')
    street = models.CharField(max_length=150, blank=True, null=True, default='')
    house = models.CharField(max_length=150, blank=True, null=True, default='')
    zip_code = models.CharField(max_length=10, blank=True, null=True, default='')
    postal_code = models.CharField(max_length=10, blank=True, null=True, default='')
    phone = PhoneNumberField(default='')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return f'Shipping Address For {self.user}'


class Order(models.Model):
    ORDERED ='ordered'
    SHIPPED = 'shipped'

    STATUS_CHOICES = (
        (ORDERED, 'Ordered'),
        (SHIPPED, 'Shipped')
    )

    PAYMENT_METHODS = [
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('cash_on_delivery', 'Cash on Delivery'),
    ]

    PRODUCT_TYPE = [
        ('auction', 'Auction'),
        ('direct_buy', 'Direct Buy'),
    ]

    BALANCE_TYPE = [
        ('debit', 'Debit'),
        ('credit', 'Credit'),
    ]


    order_uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True, db_index=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    billing = models.ForeignKey(BillingAddress, on_delete=models.CASCADE, blank=True, null=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS, blank=True, null=True)
    product_type = models.CharField(max_length=20, choices=PRODUCT_TYPE, blank=True, null=True)
    quantity = models.PositiveIntegerField()
    paid = models.BooleanField(default=False)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    balance_type = models.CharField(max_length=20, choices=BALANCE_TYPE, blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=ORDERED)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

Ankand-Auction/auctions/forms.py
from .models import *
from django import forms
from django.forms import ModelForm
from users.widgets import StateWidget, CityWidget


class ProductSearchForm(forms.Form):
    query = forms.CharField(label='Search')

    
class CreateAuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ['title', 'category', 'description', 'details_description', 'type', 'price', 'reserve_price', 'bid_increments', 'direct_buy', 'quantity', 'image', 'image1', 'image2', 'condition', 'expired_date', 'status']
        widgets = {
            'expired_date':forms.TextInput(attrs={'type':'datetime-local'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['direct_buy'].required = False
        self.fields['reserve_price'].required = False
        self.fields['price'].required = False
    
    # def clean_direct_buy(self):
    #     direct_buy = self.cleaned_data['direct_buy']
    #     if direct_buy is not None and direct_buy < 1:
    #         raise forms.ValidationError("Direct Buy value must be at least 1.")
    #     return direct_buy


class OrderForm(forms.Form):
    auction_id = forms.IntegerField(widget=forms.HiddenInput())
    quantity = forms.IntegerField(min_value=1)
    paid_amount = forms.IntegerField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone = forms.CharField()
    email = forms.CharField()
    street = forms.CharField()
    state = forms.CharField()
    house = forms.CharField()
    postal_code = forms.CharField()
    zip_code = forms.CharField()
    address=forms.CharField()


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)


class BillingAddressForm(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
    phone = PhoneNumberField()

    class Meta:
        model = BillingAddress
        fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'state', 'city', 'street', 'zip_code','postal_code', 'house', 'same_as_shipping']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})


class ShippingAddressForm(forms.ModelForm):
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
    phone = PhoneNumberField()

    class Meta:
        model = ShippingAddress
        fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'state', 'city', 'street', 'zip_code','postal_code', 'house']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})
            field.required = False


class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		fields = ("comment","rate")

Ankand-Auction/templates/auctions/bid-details.html
{% extends '_base.html' %}
{% load static %}
{% load custom_filters %}
{% block contents %}
<style>
    figure.zoom {
        background-position: 50% 50%;
        position: relative;
        overflow: hidden;
        cursor: zoom-in;
        background-size: 1000px;
      }
      figure.zoom img:hover {
        opacity: 0;
    }
      figure.zoom img {
        transition: transform: 0.5s;
        display: block;
      }
</style>

<script>
    function zoom(e){
        var zoomer = e.currentTarget;
        e.offsetX ? offsetX = e.offsetX : offsetX = e.touches[0].pageX
        e.offsetY ? offsetY = e.offsetY : offsetX = e.touches[0].pageX
        x = offsetX/zoomer.offsetWidth*100
        y = offsetY/zoomer.offsetHeight*100
        zoomer.style.backgroundPosition = x + '% ' + y + '%';
    }
</script>

<div class="inner-banner">
    <div class="container">
        <h2 class="inner-banner-title  wow fadeInLeft" data-wow-duration="1.5s" data-wow-delay=".4s">Bid Details
        </h2>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Bid Details</li>
            </ol>
        </nav>
    </div>
</div>


<div class="auction-details-section pt-120 pb-120">
    <img alt="image" src="{% static 'images/bg/section-bg.png' %}" class="img-fluid section-bg-top">
    <img alt="image" src="{% static 'images/bg/section-bg.png' %}" class="img-fluid section-bg-bottom">
    <div class="container">
        <div class="row g-4 mb-50">
            <div
                class="col-xl-6 col-lg-7 d-flex flex-row align-items-start justify-content-lg-start justify-content-center flex-md-nowrap flex-wrap gap-4">
                <ul class="nav small-image-list d-flex flex-md-column flex-row justify-content-center gap-4  wow fadeInDown"
                    data-wow-duration="1.5s" data-wow-delay=".4s">
                    {% if auction.image %}
                    <li class="nav-item">
                        <div id="details-img1" data-bs-toggle="pill" data-bs-target="#gallery-img1"
                            aria-controls="gallery-img1">
                            <img alt="image" src="{{ auction.image.url }}" class="img-fluid">
                        </div>
                    </li>
                    {% endif %}
                    {% if auction.image1 %}
                    <li class="nav-item">
                        <div id="details-img2" data-bs-toggle="pill" data-bs-target="#gallery-img2"
                            aria-controls="gallery-img2">
                            <img alt="image" src="{{ auction.image1.url }}" class="img-fluid">
                        </div>
                    </li>
                    {% endif %}
                    {% if auction.image2 %}
                    <li class="nav-item">
                        <div id="details-img3" data-bs-toggle="pill" data-bs-target="#gallery-img3"
                            aria-controls="gallery-img3">
                            <img alt="image" src="{{ auction.image2.url }}" class="img-fluid">
                        </div>
                    </li>
                    {% endif %}
                </ul>
                <div class="tab-content mb-4 d-flex justify-content-lg-start justify-content-center  wow fadeInUp"
                    data-wow-duration="1.5s" data-wow-delay=".4s">
                    {% if auction.image %}
                    <div class="tab-pane big-image show active" id="gallery-img1">
                        <figure class="zoom" onmousemove="zoom(event)" style="background-image: url({{ auction.image.url }});">
                            <img src="{{ auction.image.url }}" style=" height: 410px; width: 500px;"/>
                          </figure>
                    </div>
                    {% endif %}
                    {% if auction.image1 %}
                    <div class="tab-pane big-image fade" id="gallery-img2">
                        <figure class="zoom" onmousemove="zoom(event)" style="background-image: url({{ auction.image1.url }});">
                            <img src="{{ auction.image1.url }}" style="height: 410px; width: 500px;"/>
                          </figure>
                    </div>
                    {% endif %}
                    {% if auction.image2 %}
                    <div class="tab-pane big-image fade" id="gallery-img3">
                        <figure class="zoom" onmousemove="zoom(event)" style="background-image: url({{ auction.image2.url }});">
                            <img src="{{ auction.image2.url }}" style="height: 410px; width: 500px;"/>
                          </figure>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-xl-6 col-lg-5">
                <div class="auction-details-right wow fadeInDown" data-wow-duration="1.5s" data-wow-delay=".2s">
                    <h3>{{ auction.title }}</h3>
                    <h6> Author: {{ auction.author }}</h6>
                    <p class="para">{{ auction.description }}</p>
                    <p class="para">{{ auction.details_description|truncatechars:300 }}</p>
                    <h4>
                    {% if auction.type == 'auction' %}
                    {% if auction.winnerBid %}
                        Winning Price:
                    {% else %}
                        Bidding Price:
                    {% endif %}
                        <span> ${{ auction.price }}</span>
                    {% else %}
                        Sold Price: <span> ${{ auction.direct_buy }}</span>
                    {% endif %}
                    </h4>

                        <div class="form-title" style="margin-bottom: 0px;">
                            {% if auction.winnerBid and auction.winnerBid.type == 'auction' %}
                                <h5> Winner: {{auction.winnerBid.user.username}}</h5>
                            {% elif auction.winnerBid and auction.winnerBid.type == 'buy-it-now' %}
                                <h5> Direct Sold</h5>
                            {% else %}
                                <h5> Winner: Nobody</h5>
                            {% endif %}
                            <h6>Status:
                            {% if auction.winnerBid %}
                                Sold
                            {% else %}
                                Unsold
                            {% endif %}
                            </h6>
                        </div>
                </div>
            </div>
            <hr>

            <div class="testimonial-single style2 hover-border1 wow fadeInDown">
                <div class="testi-content">
                    <p class="para">Bidding involves placing offers to purchase items or services, often in competitive environments such as auctions or online marketplaces.</p>
                    <p class="para">All the bidding lists are here.</p>
                </div>
            </div>

            <div class="col-xl-6 col-lg-5">
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">User</th>
                        <th scope="col">Customer Username</th>
                        <th scope="col">Bid Amount</th>
                        <th scope="col">Created Date</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for bid in page_obj %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <th><img class="rounded-circle article-img" src="{{ bid.user.profile_picture_url }}" height="30px;" width="30px;"></th>
                            <td>
                            {{ bid.user.username|hide_middle_chars }}
                            </td>
                            <td>$ {{ bid.bid_amount|floatformat:"2" }}</td>
                            <td><small class="text-muted">{{ bid.created_at }}</small></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% include '_partials/_paginate.html' with alignment='float-end' %}
        </div>
    </div>
</div>

{% endblock %}

Ankand-Auction/templates/auctions/create.html
{% extends 'dashboard/_index.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block dashboard_contents %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger{% endif %}
            {% if message.tags == 'success' %}alert-success{% endif %}
            {% if message.tags == 'info' %}alert-info{% endif %}">
        {{ message }}
    </div>
    {% endfor %}
</div>

<div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel"
aria-labelledby="v-pills-profile-tab">
<div class="dashboard-profile">
    <div class="owner">
        <div class="content">
            <h3>Create A New auction</h3>
        </div>
    </div>
    <div class="form-wrapper">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-6">
                    {{ form|crispy }}
                </div>
                <div class="col-12">
                    <div class="button-group">
                        <button type="submit" class="eg-btn profile-btn">Submit auction</button>
                        <button class="eg-btn cancel-btn">Cancel</button>
                    </div>
                </div>
            </div>
        </form> 
    </div>
</div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        // Hide the additional div initially
        $('#div_id_price').hide();
        $('#div_id_reserve_price').hide();
        $('#div_id_direct_buy').hide();
        $('#div_id_bid_increments').hide();

        // Add onchange event listener to the select element
        $('#id_type').change(function() {
            var selectedValue = $(this).find("option:selected").val();
            var price = $('#div_id_price')
            var reserve_price = $('#div_id_reserve_price')
            var direct_buy = $('#div_id_direct_buy')
            var bid_increments = $('#div_id_bid_increments')

            if (selectedValue === 'auction') {
                price.show();
                reserve_price.show()
                bid_increments.show()
                direct_buy.hide()
                price.required = true;
                reserve_price.required = true;
                direct_buy.required = false;
            } else if (selectedValue === 'buy-it-now') {
                price.hide();
                reserve_price.hide()
                bid_increments.hide()
                direct_buy.show()
                price.required = false;
                reserve_price.required = false;
                direct_buy.required = true;
            } else if (selectedValue === 'auction & buy-it-now') {
                price.show();
                reserve_price.show()
                direct_buy.show()
                bid_increments.show()
                price.required = true;
                reserve_price.required = true;
                direct_buy.required = true;
            } else {
                price.hide();
                reserve_price.hide()
                direct_buy.hide()
                bid_increments.hide()
                price.required = false;
                reserve_price.required = false;
                direct_buy.required = false;
            }

        });

        // Trigger change event once on page load to get the initial selected value
        $('#id_type').change();
    });
</script>
{% endblock %}